from models.schemas import ResearchResult


def to_markdown(result: ResearchResult) -> str:
    """Convert a ResearchResult to a complete, human-readable Markdown document."""
    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────────
    lines += [
        f"# Literature Review: {result.topic}",
        "",
        f"*Generated by Literature Review AI · {len(result.papers)} papers analysed*",
        "",
        "---",
        "",
    ]

    # ── Table of Contents ────────────────────────────────────────────
    lines += [
        "## Table of Contents",
        "",
        "1. [Introduction](#introduction)",
        "2. [Research Themes](#research-themes)",
        "3. [Synthesis](#synthesis)",
        "4. [Research Gaps & Future Directions](#research-gaps--future-directions)",
        "5. [Implications](#implications)",
        "6. [Paper Summaries](#paper-summaries)",
        "7. [References](#references)",
        "",
        "---",
        "",
    ]

    # ── 1. Introduction ──────────────────────────────────────────────
    lines += ["## Introduction", "", result.review.introduction, "", "---", ""]

    # ── 2. Research Themes ───────────────────────────────────────────
    lines += ["## Research Themes", ""]
    for theme in result.review.themes:
        paper_count = len(theme.paper_ids)
        lines += [
            f"### {theme.name} ({paper_count} papers)",
            "",
            theme.description,
            "",
        ]
    lines += ["---", ""]

    # ── 3. Synthesis ─────────────────────────────────────────────────
    lines += ["## Synthesis", "", result.review.synthesis, "", "---", ""]

    # ── 4. Gaps & Future Directions ──────────────────────────────────
    lines += ["## Research Gaps & Future Directions", "", "### Research Gaps", ""]
    for gap in result.review.research_gaps:
        lines.append(f"- {gap}")
    lines += ["", "### Future Directions", ""]
    for direction in result.review.future_directions:
        lines.append(f"- {direction}")
    lines += ["", result.review.conclusion, "", "---", ""]

    # ── 5. Implications ──────────────────────────────────────────────
    lines += ["## Implications", ""]
    sections = [
        ("Theoretical", result.implications.theoretical),
        ("Practical", result.implications.practical),
        ("Policy", result.implications.policy),
        ("Future Research Questions", result.implications.future_research),
    ]
    for title, items in sections:
        if items:
            lines += [f"### {title}", ""]
            for item in items:
                lines.append(f"- {item}")
            lines.append("")
    lines += ["---", ""]

    # ── 6. Paper Summaries ───────────────────────────────────────────
    lines += ["## Paper Summaries", ""]
    for i, summary in enumerate(
        sorted(result.summaries, key=lambda s: s.relevance_score, reverse=True), 1
    ):
        authors_str = ", ".join(summary.authors[:3])
        if len(summary.authors) > 3:
            authors_str += " et al."
        lines += [
            f"### {i}. {summary.title}",
            f"*{authors_str} ({summary.year or 'n.d.'}) · Relevance: {summary.relevance_score:.0%}*",
            "",
        ]
        lines += ["**Key Contributions**", ""]
        for contrib in summary.key_contributions:
            lines.append(f"- {contrib}")
        lines += [
            "",
            f"**Methodology:** {summary.methodology}",
            "",
            f"**Findings:** {summary.findings}",
            "",
            f"**Limitations:** {summary.limitations}",
            "",
        ]
    lines += ["---", ""]

    # ── 7. References ────────────────────────────────────────────────
    lines += ["## References", ""]
    for i, ref in enumerate(result.references, 1):
        lines.append(f"{i}. {ref}")
    lines.append("")

    return "\n".join(lines)
