from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from models.schemas import ResearchResult
import io


def to_docx(result: ResearchResult) -> bytes:
    """Export a ResearchResult to a Word document (.docx) and return bytes."""
    doc = Document()

    # ── Page margins ────────────────────────────────────────────────
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.25)
        section.right_margin = Inches(1.25)

    # ── Title ────────────────────────────────────────────────────────
    title = doc.add_heading(f"Literature Review: {result.topic}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph(f"{len(result.papers)} papers analysed · Generated by Literature Review AI")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.add_page_break()

    # ── Introduction ─────────────────────────────────────────────────
    doc.add_heading("1. Introduction", 1)
    doc.add_paragraph(result.review.introduction)

    # ── Research Themes ──────────────────────────────────────────────
    doc.add_heading("2. Research Themes", 1)
    for theme in result.review.themes:
        doc.add_heading(f"{theme.name} ({len(theme.paper_ids)} papers)", 2)
        doc.add_paragraph(theme.description)

    # ── Synthesis ────────────────────────────────────────────────────
    doc.add_heading("3. Synthesis", 1)
    doc.add_paragraph(result.review.synthesis)

    # ── Research Gaps ────────────────────────────────────────────────
    doc.add_heading("4. Research Gaps", 1)
    for gap in result.review.research_gaps:
        p = doc.add_paragraph(gap, style="List Bullet")

    doc.add_heading("5. Future Directions", 1)
    for direction in result.review.future_directions:
        doc.add_paragraph(direction, style="List Bullet")

    doc.add_heading("Conclusion", 2)
    doc.add_paragraph(result.review.conclusion)

    # ── Implications ─────────────────────────────────────────────────
    doc.add_heading("6. Implications", 1)
    impl_sections = [
        ("Theoretical Implications", result.implications.theoretical),
        ("Practical Implications", result.implications.practical),
        ("Policy Implications", result.implications.policy),
        ("Future Research Questions", result.implications.future_research),
    ]
    for heading, items in impl_sections:
        if items:
            doc.add_heading(heading, 2)
            for item in items:
                doc.add_paragraph(item, style="List Bullet")

    # ── Paper Summaries ──────────────────────────────────────────────
    doc.add_page_break()
    doc.add_heading("7. Paper Summaries", 1)
    for i, summary in enumerate(
        sorted(result.summaries, key=lambda s: s.relevance_score, reverse=True), 1
    ):
        authors_str = ", ".join(summary.authors[:3])
        if len(summary.authors) > 3:
            authors_str += " et al."
        doc.add_heading(f"{i}. {summary.title}", 2)
        meta = doc.add_paragraph(f"{authors_str} · {summary.year or 'n.d.'} · Relevance: {summary.relevance_score:.0%}")
        meta.runs[0].font.color.rgb = RGBColor(0x66, 0x66, 0x66)

        doc.add_heading("Key Contributions", 3)
        for contrib in summary.key_contributions:
            doc.add_paragraph(contrib, style="List Bullet")

        doc.add_heading("Methodology", 3)
        doc.add_paragraph(summary.methodology)
        doc.add_heading("Findings", 3)
        doc.add_paragraph(summary.findings)
        doc.add_heading("Limitations", 3)
        doc.add_paragraph(summary.limitations)

    # ── References ───────────────────────────────────────────────────
    doc.add_page_break()
    doc.add_heading("References", 1)
    for i, ref in enumerate(result.references, 1):
        p = doc.add_paragraph()
        p.paragraph_format.first_line_indent = Inches(-0.5)
        p.paragraph_format.left_indent = Inches(0.5)
        p.add_run(f"{i}.  {ref}")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
